### ISSUE TITLE
Logo for BakeMe

### ISSUE THREAD

**Issue by familqasimov** [georkost4/BakeMe#1]
Hi friend. I'm graphic designer. I have studied your work and I think a logo will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![bakeme](https://user-images.githubusercontent.com/36432269/40327981-d5e86ef4-5d55-11e8-8bcc-a01c2768a83f.png)

Best regard

**Comment by georkost4** [comment]
@familqasimov Hi my friend , thank you for contacting me . As this project is still in progress and is not submitted for review  I would not be accepting any PR . But I would gladly accept any logo via e-mail , they look pretty good by the way  nice work you have there.
